# Generated by Django 4.2.7 on 2025-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_unique_ref', models.CharField(help_text='Unique vehicle identifier (VehicleUniqueRef)', max_length=50, unique=True)),
                ('fleet_number', models.CharField(blank=True, help_text='Fleet number or registration', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this vehicle available for tracking?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['vehicle_unique_ref'],
                'indexes': [models.Index(fields=['is_active'], name='vehicles_is_acti_fa11c1_idx')],
            },
        ),
    ]
